import type { Gym, EquipmentCatalog, GymEquipment, GymFacility } from "./types"

export const EQUIPMENT_CATALOG: EquipmentCatalog[] = [
  {
    id: "eq1",
    name: "Cybex Chest Press",
    brand: "Cybex",
    category: "upper",
    type: "machine",
    imageUrl: "/cybex-vr2-chest-press.jpg",
    metadata: "핀 선택식의 체스트 프레스 머신으로, 초보자부터 숙련자까지 사용 가능합니다.",
  },
  {
    id: "eq2",
    name: "Hammer Strength Shoulder Press",
    brand: "Hammer Strength",
    category: "upper",
    type: "machine",
    imageUrl: "/hammer-strength-plate-loaded-iso-lateral-shoulder-press-charcoal-black-1000x1000_1200x1200.webp",
    metadata: "양팔 독립 운동이 가능한 플레이트 로드 식 숄더 프레스 머신입니다.",
  },
  {
    id: "eq3",
    name: "TechnoGym Leg Press Machine",
    brand: "TechnoGym",
    category: "lower",
    type: "machine",
    imageUrl: "/technogym-leg-press-machine.jpg",
    metadata: "고급 레그 프레스 머신으로 매우 안정적입니다.",
  },
  {
    id: "eq4",
    name: "Cybex Eagle Leg Extension",
    brand: "Cybex",
    category: "lower",
    type: "machine",
    imageUrl: "/cybex-eagle-leg-extension.webp",
    metadata: "대퇴사두근 중심의 레그 익스텐션 머신입니다.",
  },
  {
    id: "eq5",
    name: "Hammer Strength Leg Curl Machine",
    brand: "Hammer Strength",
    category: "lower",
    type: "machine",
    imageUrl: "/hammer-strength-select-leg-curl.jpg",
    metadata: "해스트링 운동에 최적화된 머신입니다.",
  },
  {
    id: "eq6",
    name: "Abdominal Crunch Machine",
    brand: "TechnoGym",
    category: "core",
    type: "machine",
    imageUrl: "/abdominal_crunch_machine.jpg",
    metadata: "복부 크런치 전용 머신입니다.",
  },
  {
    id: "eq7",
    name: "Cybex torso rotation",
    brand: "Cybex",
    category: "core",
    type: "machine",
    imageUrl: "/cybex-torso-rotation.webp",
    metadata: "코어 안정화 및 외복사근 타겟 머신입니다.",
  },
  {
    id: "eq8",
    name: "Precor TRM835 Treadmill",
    brand: "Precor",
    category: "cardio",
    type: "machine",
    imageUrl: "/precor-trm835-treadmill.webp",
    metadata: "프리미엄 러닝머신으로 조용하고 부드럽습니다.",
  },
  {
    id: "eq9",
    name: "Keiser M3i Indoor Bike",
    brand: "Keiser",
    category: "cardio",
    type: "machine",
    imageUrl: "/keiser-m3i-indoor-bike.jpg",
    metadata: "자동 저항 조절 기능이 있는 고급 실내 자전거입니다.",
  },
  {
    id: "eq10",
    name: "Elliptical Trainer",
    brand: "TechnoGym",
    category: "cardio",
    type: "machine",
    imageUrl: "/training-floor.jpg",
    metadata: "저충격 유산소 운동이 가능한 타원형 머신입니다.",
  },
  {
    id: "eq11",
    name: "Power Rack",
    brand: "Rogue",
    category: "freeweight",
    type: "rack",
    imageUrl: "/free-weights-section.jpg",
    metadata: "스쿼트, 벤치프레스, 데드리프트 등 모든 프리웨이트 운동이 가능합니다.",
  },
  {
    id: "eq12",
    name: "Barbell Set (20kg)",
    brand: "Rogue",
    category: "freeweight",
    type: "freeweight",
    imageUrl: "/gym-dumbbells-area.jpg",
    metadata: "IWF 표준 올림픽 바벨과 플레이트 세트입니다.",
  },
  {
    id: "eq13",
    name: "Dumbbell Set (5-50kg)",
    brand: "Bowflex",
    category: "freeweight",
    type: "freeweight",
    imageUrl: "/free-weights-section.jpg",
    metadata: "전 범위의 덤벨 세트로 다양한 운동이 가능합니다.",
  },
  {
    id: "eq14",
    name: "Adjustable Bench",
    brand: "Rogue",
    category: "freeweight",
    type: "bench",
    imageUrl: "/training-floor.jpg",
    metadata: "각도 조절이 가능한 프리미엄 벤치입니다.",
  },
  {
    id: "eq15",
    name: "Cable Machine",
    brand: "Cybex",
    category: "upper",
    type: "machine",
    imageUrl: "/exercise-equipment.jpg",
    metadata: "양쪽 풀리가 있는 고급 케이블 머신입니다.",
  },
]

export const GYMS: Gym[] = [
  {
    id: "gym1",
    name: "수원 핏짐",
    address: "수원시 영통구 대덕동",
    phone: "031-123-4567",
    description:
      "프리웨이트 중심의 헬스장입니다. 경험 많은 트레이너들이 상주하고 있어 초보자도 안심하고 이용할 수 있습니다. 넓은 스쿼트 랙 존과 데드리프트 플랫폼이 특징입니다.",
    image: "/modern-gym-with-weights.jpg",
    images: ["/modern-gym-with-weights.jpg", "/free-weights-section.jpg", "/gym-dumbbells-area.jpg"],
    hours: "06:00 - 23:00",
  },
  {
    id: "gym2",
    name: "영통 스트롱짐",
    address: "수원시 영통구 영통동",
    phone: "031-234-5678",
    description:
      "하체 전문 헬스장으로, 최신 레그 머신들과 스미스머신이 풍부합니다. 하체 운동에 관심 있는 분들에게 강력히 추천합니다.",
    image: "/leg-press-and-cardio-equipment.jpg",
    images: ["/leg-press-and-cardio-equipment.jpg", "/leg-equipment-gym.jpg", "/leg-extension-machine.jpg"],
    hours: "06:00 - 22:00",
  },
  {
    id: "gym3",
    name: "인계 프리미엄 피트니스",
    address: "수원시 영통구 인계동",
    phone: "031-345-6789",
    description:
      "프리미엄 시설을 갖춘 종합 피트니스센터입니다. 사우나, 샤워실, 라운지 등 부대시설이 완벽하고 유산소 기구가 충실합니다.",
    image: "/luxury-fitness-facility-with-sauna.jpg",
    images: ["/luxury-fitness-facility-with-sauna.jpg", "/cardio-machines-gym.jpg", "/training-floor.jpg"],
    hours: "06:00 - 23:30",
  },
]

export const GYM_EQUIPMENT: GymEquipment[] = [
  // 수원 핏짐 (gym1) - 프리웨이트 중심
  { id: "ge1", gymId: "gym1", equipmentCatalogId: "eq1", quantity: 1 },
  { id: "ge2", gymId: "gym1", equipmentCatalogId: "eq2", quantity: 1 },
  { id: "ge3", gymId: "gym1", equipmentCatalogId: "eq3", quantity: 2 },
  { id: "ge4", gymId: "gym1", equipmentCatalogId: "eq6", quantity: 1 },
  { id: "ge5", gymId: "gym1", equipmentCatalogId: "eq8", quantity: 3 },
  { id: "ge6", gymId: "gym1", equipmentCatalogId: "eq11", quantity: 3, note: "올림픽 바 전용" },
  { id: "ge7", gymId: "gym1", equipmentCatalogId: "eq12", quantity: 5 },
  { id: "ge8", gymId: "gym1", equipmentCatalogId: "eq13", quantity: 2 },
  { id: "ge9", gymId: "gym1", equipmentCatalogId: "eq14", quantity: 3 },

  // 영통 스트롱짐 (gym2) - 하체 중심
  { id: "ge10", gymId: "gym2", equipmentCatalogId: "eq3", quantity: 3 },
  { id: "ge11", gymId: "gym2", equipmentCatalogId: "eq4", quantity: 2 },
  { id: "ge12", gymId: "gym2", equipmentCatalogId: "eq5", quantity: 2 },
  { id: "ge13", gymId: "gym2", equipmentCatalogId: "eq1", quantity: 1 },
  { id: "ge14", gymId: "gym2", equipmentCatalogId: "eq9", quantity: 4 },
  { id: "ge15", gymId: "gym2", equipmentCatalogId: "eq10", quantity: 2 },
  { id: "ge16", gymId: "gym2", equipmentCatalogId: "eq12", quantity: 3 },

  // 인계 프리미엄 피트니스 (gym3) - 균형잡힌 구성
  { id: "ge17", gymId: "gym3", equipmentCatalogId: "eq1", quantity: 2 },
  { id: "ge18", gymId: "gym3", equipmentCatalogId: "eq2", quantity: 1 },
  { id: "ge19", gymId: "gym3", equipmentCatalogId: "eq3", quantity: 2 },
  { id: "ge20", gymId: "gym3", equipmentCatalogId: "eq4", quantity: 1 },
  { id: "ge21", gymId: "gym3", equipmentCatalogId: "eq6", quantity: 1 },
  { id: "ge22", gymId: "gym3", equipmentCatalogId: "eq7", quantity: 1 },
  { id: "ge23", gymId: "gym3", equipmentCatalogId: "eq8", quantity: 5 },
  { id: "ge24", gymId: "gym3", equipmentCatalogId: "eq9", quantity: 3 },
  { id: "ge25", gymId: "gym3", equipmentCatalogId: "eq10", quantity: 3 },
  { id: "ge26", gymId: "gym3", equipmentCatalogId: "eq15", quantity: 1 },
]

export const GYM_FACILITIES: GymFacility[] = [
  { id: "f1", gymId: "gym1", facilityType: "샤워실", detail: "있음", icon: "🚿" },
  { id: "f2", gymId: "gym1", facilityType: "사우나", detail: "없음", icon: "🧖" },
  { id: "f3", gymId: "gym1", facilityType: "락커", detail: "개인 락커", icon: "🔒" },
  { id: "f4", gymId: "gym1", facilityType: "주차", detail: "가능 (20대)", icon: "🚗" },

  { id: "f5", gymId: "gym2", facilityType: "샤워실", detail: "있음", icon: "🚿" },
  { id: "f6", gymId: "gym2", facilityType: "사우나", detail: "있음", icon: "🧖" },
  { id: "f7", gymId: "gym2", facilityType: "락커", detail: "개인 락커 + 짐 보관함", icon: "🔒" },
  { id: "f8", gymId: "gym2", facilityType: "주차", detail: "가능 (15대)", icon: "🚗" },

  { id: "f9", gymId: "gym3", facilityType: "샤워실", detail: "있음 (개인 부스)", icon: "🚿" },
  { id: "f10", gymId: "gym3", facilityType: "사우나", detail: "있음 (찜질방 포함)", icon: "🧖" },
  { id: "f11", gymId: "gym3", facilityType: "락커", detail: "개인 락커 + VIP 라운지", icon: "🔒" },
  { id: "f12", gymId: "gym3", facilityType: "주차", detail: "가능 (50대 + 야외)", icon: "🚗" },
  { id: "f13", gymId: "gym3", facilityType: "카페", detail: "헬시 스낵/음료", icon: "☕" },
]
